language: objective-c
branches:
  only:
    - master
git:
  submodules: false
before_install: git submodule update --init --recursive
script: 
  - bundle exec rake spec
  - bundle exec danger || true
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
matrix:
  include:
    - osx_image: xcode7.3
      env: TRAVIS_SWIFT_VERSION=2.2
