matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode6.4
    - language: objective-c
      os: osx
      osx_image: xcode7
cache: bundler
branches:
  only:
    - master
rvm:
  - system
before_install:
  - sudo gem install bundler
  - git submodule update --init --recursive
script:
  - bundle exec rake spec
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
