language: objective-c
branches:
  only:
    - master
git:
  submodules: false
before_install: git submodule update --init --recursive
script: bundle exec rake spec
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
matrix:
  include:
    - osx_image: xcode7.2
      env: TRAVIS_SWIFT_VERSION=2.1.1
